# NumPy数值计算基础

In [3]:
import numpy as np  # 导入 NumPy 模块

a = np.array([1.1, 2.2, 3.3], dtype=np.float64)  # 指定 1 维数组的数值类型为 float64
a, a.dtype  # 查看 a 及 dtype 类型

(array([1.1, 2.2, 3.3]), dtype('float64'))

In [3]:
a.astype(int).dtype  # 将 a 的数值类型从 float64 转换为 int，并查看 dtype 类型

dtype('int64')

In [4]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.array([(1, 2), (3, 4), (5, 6)])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# 在区间 [3, 7) 中以 0.5 为步长新建数组
np.arange(3, 7, 0.5, dtype='float32')

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5], dtype=float32)

In [9]:
np.linspace(0, 10, 10, endpoint=True)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
np.linspace(0, 10, 10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.eye(5, 4,3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.fromfunction(lambda a, b: a + b, (5, 4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.],
       [4., 5., 6., 7.]])

## 一点补充
这行代码使用了`NumPy`库的`np.fromfunction`函数来生成一个数组。`np.fromfunction`函数接受两个参数：一个函数和一个形状元组。它会根据给定的形状生成一个数组，数组中的每个元素值由传入的函数计算得到。传入的函数需要接受和数组维度相同数量的索引参数，并返回对应位置的元素值。

在这个例子中，传入的函数是`lambda a, b: a + b`，它接受两个参数`a`和`b`，返回它们的和。形状元组是`(5, 4)`，意味着生成的数组将是一个5行4列的二维数组。

具体来说，这行代码会生成一个5行4列的数组，数组中每个位置`(a, b)`的值将是行索引`a`和列索引`b`的和。例如，位置(0, 0)的值是0+0=0，位置(1, 2)的值是1+2=3，以此类推。

lambda在Python中用于创建匿名函数，即没有名字的函数。它的语法结构简单，主要用于需要函数对象的地方，而这个函数的逻辑又足够简单，可以在一行内表示。
lambda函数的基本语法如下：
```python
lambda 参数列表: 表达式
```
- 参数列表：和普通函数一样，lambda函数可以有任意数量的参数，包括可选参数列表，但不能有默认参数值。
- 表达式：这是lambda函数的主体，这个表达式的计算结果就是函数的返回值。注意，lambda函数只能有一个表达式，不能包含复杂的逻辑，这个表达式不能包含命令，只能是计算并返回一个值。

In [4]:
np.fromfunction(lambda i, j: (i + 1) * (j + 1), (9, 9)) # 九九乘法表

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [5]:
np.fromfunction(lambda x, y, z: x + y - z, (3, 3, 3)) # 三维数组

array([[[ 0., -1., -2.],
        [ 1.,  0., -1.],
        [ 2.,  1.,  0.]],

       [[ 1.,  0., -1.],
        [ 2.,  1.,  0.],
        [ 3.,  2.,  1.]],

       [[ 2.,  1.,  0.],
        [ 3.,  2.,  1.],
        [ 4.,  3.,  2.]]])

In [6]:
np.fromfunction(lambda i, j: np.where(i == j, 1, 0), (4, 4)) # 单位矩阵

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [7]:
np.fromfunction(lambda i, j: (i + j) % 2, (8, 8)) # 棋盘

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])